ktor:
    application:
        modules:
            - example.com.ApplicationKt.module
    deployment:
        port: "$PORT:8080"

db:
    mongo:
        user: '$MONGO_USERNAME:root'
        password: '$MONGO_PASSWORD:root'